language: cpp
compiler:
  - gcc
  - clang

addons:
  apt:
    packages:
      - cmake
      - liblua5.1-0
      - libglfw-dev
      - libglew-dev
      - libglm-dev

before_script:
  - cmake .
  - make

script:
  - ./Wake --testing