language: cpp
compiler:
  - gcc
  - clang

addons:
  apt:
    packages:
      - liblua5.1-0-dev
      - libglfw-dev
      - libglew-dev
      - libglm-dev

cache:
  directories:
    - $HOME/cmake

install:
  - bash ./ci-install.sh

before_script:
  - ./cmake/bin/cmake .
  - make

script:
  - ./Wake --testing