language: cpp
compiler:
  - gcc

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - liblua5.1-0-dev
      - libglew-dev
      - xorg-dev
      - libglu1-mesa-dev
      - gcc-4.8
      - g++-4.8
      - unzip
      - libxinerama-dev

install:
  - bash ./ci-install.sh
  - pwd

before_script:
  - export CC=/usr/bin/gcc-4.8
  - export CXX=/usr/bin/g++-4.8
  - gcc-4.8 --version
  - pwd
  - ./cmake/bin/cmake -DGLM_INCLUDE_DIR="./glm/" . -DGLFW_INCLUDE_DIR="./glfw/include" -DGLFW_glfw_LIBRARY="./glfw/src/libglfw3.a"
  - make

script:
  - cd dist && ../Wake --testing
