language: cpp
compiler:
  - gcc

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - liblua5.1-0-dev
      - libglfw-dev
      - libglew-dev
      - xorg-dev
      - libglu1-mesa-dev
      - gcc-4.8

cache:
  directories:
    - $HOME/cmake
    - $HOME/glm

install:
  - bash ./ci-install.sh

before_script:
  - export CC=gcc-4.8
  - export CXX=g++-4.8
  - gcc-4.8 --version
  - ./cmake/bin/cmake -DGLM_INCLUDE_DIR="${HOME}/glm" .
  - make

script:
  - ./Wake --testing