language: cpp
compiler:
  - clang

addons:
  apt:
    packages:
      - liblua5.1-0-dev
      - libglfw-dev
      - libglew-dev
      - xorg-dev
      - libglu1-mesa-dev

cache:
  directories:
    - $HOME/cmake
    - $HOME/glm

install:
  - bash ./ci-install.sh

before_script:
  - ./cmake/bin/cmake -DGLM_INCLUDE_DIR="${HOME}/glm" .
  - make

script:
  - ./Wake --testing